### PR TITLE
Conditional include/exclude entire resources Closes #23

### LINKED ISSUE #23: Support conditional inclusion/exclusion of entire resources
Sometimes we want to include/exclude entire resources. Example is that kubebuilder emits a prometheus `ServiceMonitor` resource for all new operators. If the target cluster doesn't have `kube-prometheus-stack` installed, then that CRD will not be present and the deployment will fail.

Add a new root level strategy `file-if` that can wrap a resource thus:

```
{{- if .Values.some.condition }}
# Entire resource manifest
{{- end }}
```

PR for this expected very soon :smile:

### PR DESCRIPTION
**Pull request by fireflycons**
* Add a new root level strategy `file-if` that can wrap an entire resource
* Validate usage of this strategy when config is loaded
* Add tests for this validation
* Update sample-0300 to use `file-if` on new prometheus `ServiceMonitor` resource
* Update READMEs

### CODE REVIEW

File: pkg/config/config.go [hunk 1]
```diff
@@ -215,6 +216,33 @@ func (c *ChartConfig) GetFormattedKeyWithDefaultValue(xc *XPathConfig, prefix st
...
+						return fmt.Errorf("'%s' cannot use strategy '%s' at root level", manifest, strategy)
+					}
+				} else if strategy == XPathStrategyFileIf {
+					return fmt.Errorf("'%s' cannot use strategy '%s' at non-root level", manifest, strategy)
+				}
+			}
+		}
+	}
+
+	return nil
```
Comment (yeahdongcn) [inline pkg/config/config.go:243]: These could be simplified to 
```golang
if xpath != XPathRoot || strategy != XPathStrategyFileIf {
    return fmt.Errorf(...)
}
```

File: test/output/0300/no-ns-chart.config [hunk 2]
```diff
@@ -21,3 +23,7 @@ fileConfig:
   test/output/0300/no-ns-chart-generated/my-role-role.yaml: {}
   test/output/0300/no-ns-chart-generated/my-rolebinding-rb.yaml: {}
   test/output/0300/no-ns-chart-generated/my-service-account-sa.yaml: {}
+  test/output/0300/no-ns-chart-generated/sample-0300-controller-manager-metrics-monitor-servicemonitor.yaml:
+    "":
```
Comment (yeahdongcn) [inline test/output/0300/no-ns-chart.config:27]: `XPathRoot` looks evident in the code, but using `""` here may confuse the users. Do you have any better ideas?

File: pkg/config/config.go (hunk 1 above)
Comment (fireflycons) [reply pkg/config/config.go]: Removed one level of if nesting, but not the way you suggested as that causes several test failures.

File: test/output/0300/no-ns-chart.config (hunk 2 above)
Comment (fireflycons) [reply test/output/0300/no-ns-chart.config:27]: I thought about this at the time. The issue we have is that this key in the config represents an XPath, and that the required XPath is root. 
Considered something muckier like `.` or `/` to represent root which would have to be resolved to `""` as the config is loaded, however these characters may still need to be quoted.
Could possibly use `root` as a key, since AFAIK that doesn't appear as a root level property on any known resource, but that's not to stop someone creating it as part of a CRD.

File: pkg/config/config.go (hunk 1 above)
Comment (yeahdongcn) [reply pkg/config/config.go]: Sorry, please see the latest commit. `make test` reports no error.

Comment (fireflycons) [reply pkg/config/config.go]: Ahh - I see. 

What you've actually committed is different to what you put in the comment above, but a neat trick though.
